In [2]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array(range(2))
c = np.array((1, 2, 3, 4))
print(a)
print(b)
print(c)

[1 2 3 4]
[0 1]
[1 2 3 4]


In [7]:
a.shape

(4,)

In [17]:
b = np.array([range(3), range(3)])
b

array([[0, 1, 2],
       [0, 1, 2]])

In [16]:
b.shape

(2, 3)

In [19]:
b.ndim

2

In [20]:
b.nbytes

48

## Functions


In [23]:
a = np.arange(start=0, stop=100, step=0.2)

In [24]:
a.size

500

In [25]:
np.random.permutation(a)

array([52.8, 56.2, 55. , 37.2, 64. , 80.6, 12.6, 32.6,  0. , 59.6, 97.6,
       36. , 60. ,  0.4,  0.2, 29.8, 23. , 83.4, 35.4, 72. , 32. , 23.2,
        7.4, 18.6, 27.2, 42. , 31.8, 60.4,  7.6, 21.4,  7.2, 39. , 48. ,
       88.2, 71. , 77. , 57.6, 99.6, 51. ,  8.2,  2.6, 94.4, 65. , 44.2,
       67.6, 67.8, 32.8, 65.8, 50.6,  9.2, 25.8, 46.4, 39.8, 46. , 22.6,
       50.8, 39.2, 13.8, 89.4, 73.8,  3.2, 85.2, 29.6, 59.4, 94.6, 29.2,
       67.4, 37.8, 97.2, 64.2, 58.4, 36.2, 69. , 51.8, 45. , 68.6, 78.6,
       10.4,  9.8,  4.8, 93.2, 62. , 75. , 68.8, 14. , 24.4, 94.2, 71.4,
       97. , 69.2, 79.4,  5. , 53. , 50. , 58.8, 48.8, 95.8, 87.4,  4.2,
       30.6, 30. , 13.2, 86.4, 18. , 75.2, 64.4, 64.6, 59.8, 75.4, 12.8,
       11.2, 96.4, 29.4,  5.8, 14.2, 10. , 76.4,  1.6, 42.4, 59. , 15.8,
       87.8, 17. , 38.2, 41.8, 91.6, 93.8, 89.6, 89.8, 93.6, 23.6, 88.6,
       13. , 16.6, 48.6, 88.4, 22.8, 17.2, 72.2, 68. , 21. , 16.2, 47.4,
       43.4, 69.8,  2. , 52.4, 53.4, 45.2, 53.2, 31

In [29]:
reshaped = np.reshape(a, (2, 10, 5, 5))

In [31]:
reshaped[:].size

500

In [34]:
a[:250].size

250

In [40]:
reshaped[:1, :, 2:, 2:4]

array([[[[ 2.4,  2.6],
         [ 3.4,  3.6],
         [ 4.4,  4.6]],

        [[ 7.4,  7.6],
         [ 8.4,  8.6],
         [ 9.4,  9.6]],

        [[12.4, 12.6],
         [13.4, 13.6],
         [14.4, 14.6]],

        [[17.4, 17.6],
         [18.4, 18.6],
         [19.4, 19.6]],

        [[22.4, 22.6],
         [23.4, 23.6],
         [24.4, 24.6]],

        [[27.4, 27.6],
         [28.4, 28.6],
         [29.4, 29.6]],

        [[32.4, 32.6],
         [33.4, 33.6],
         [34.4, 34.6]],

        [[37.4, 37.6],
         [38.4, 38.6],
         [39.4, 39.6]],

        [[42.4, 42.6],
         [43.4, 43.6],
         [44.4, 44.6]],

        [[47.4, 47.6],
         [48.4, 48.6],
         [49.4, 49.6]]]])

In [57]:
a.reshape(2, 250)[::-5]

array([[50. , 50.2, 50.4, 50.6, 50.8, 51. , 51.2, 51.4, 51.6, 51.8, 52. ,
        52.2, 52.4, 52.6, 52.8, 53. , 53.2, 53.4, 53.6, 53.8, 54. , 54.2,
        54.4, 54.6, 54.8, 55. , 55.2, 55.4, 55.6, 55.8, 56. , 56.2, 56.4,
        56.6, 56.8, 57. , 57.2, 57.4, 57.6, 57.8, 58. , 58.2, 58.4, 58.6,
        58.8, 59. , 59.2, 59.4, 59.6, 59.8, 60. , 60.2, 60.4, 60.6, 60.8,
        61. , 61.2, 61.4, 61.6, 61.8, 62. , 62.2, 62.4, 62.6, 62.8, 63. ,
        63.2, 63.4, 63.6, 63.8, 64. , 64.2, 64.4, 64.6, 64.8, 65. , 65.2,
        65.4, 65.6, 65.8, 66. , 66.2, 66.4, 66.6, 66.8, 67. , 67.2, 67.4,
        67.6, 67.8, 68. , 68.2, 68.4, 68.6, 68.8, 69. , 69.2, 69.4, 69.6,
        69.8, 70. , 70.2, 70.4, 70.6, 70.8, 71. , 71.2, 71.4, 71.6, 71.8,
        72. , 72.2, 72.4, 72.6, 72.8, 73. , 73.2, 73.4, 73.6, 73.8, 74. ,
        74.2, 74.4, 74.6, 74.8, 75. , 75.2, 75.4, 75.6, 75.8, 76. , 76.2,
        76.4, 76.6, 76.8, 77. , 77.2, 77.4, 77.6, 77.8, 78. , 78.2, 78.4,
        78.6, 78.8, 79. , 79.2, 79.4, 

In [67]:
a = a.reshape(2, 250)
a[:, ::-5]

array([[49.8, 48.8, 47.8, 46.8, 45.8, 44.8, 43.8, 42.8, 41.8, 40.8, 39.8,
        38.8, 37.8, 36.8, 35.8, 34.8, 33.8, 32.8, 31.8, 30.8, 29.8, 28.8,
        27.8, 26.8, 25.8, 24.8, 23.8, 22.8, 21.8, 20.8, 19.8, 18.8, 17.8,
        16.8, 15.8, 14.8, 13.8, 12.8, 11.8, 10.8,  9.8,  8.8,  7.8,  6.8,
         5.8,  4.8,  3.8,  2.8,  1.8,  0.8],
       [99.8, 98.8, 97.8, 96.8, 95.8, 94.8, 93.8, 92.8, 91.8, 90.8, 89.8,
        88.8, 87.8, 86.8, 85.8, 84.8, 83.8, 82.8, 81.8, 80.8, 79.8, 78.8,
        77.8, 76.8, 75.8, 74.8, 73.8, 72.8, 71.8, 70.8, 69.8, 68.8, 67.8,
        66.8, 65.8, 64.8, 63.8, 62.8, 61.8, 60.8, 59.8, 58.8, 57.8, 56.8,
        55.8, 54.8, 53.8, 52.8, 51.8, 50.8]])

In [90]:
a[np.random.randint(low=0, high=2), np.random.randint(low=0, high=250)] = -1200

indexes = np.where(a==-1200)
for x, y in zip(indexes[0], indexes[1]):
    a[x][y] = 1
print(indexes, np.where(a==-1200))

(array([1]), array([202])) (array([], dtype=int64), array([], dtype=int64))
